server {
    listen 8080;
    server_name localhost;

    if ($host = 'cafe-search-678473793429.asia-northeast1.run.app') {
        return 301 https://cafe-search.immersed-in-knowing.com$request_uri;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
